[include mmu_klipperscreen.conf]
[include conf.d/*.conf]
[main]
job_complete_timeout: 0
job_error_timeout: 0
show_cursor: False
default_printer: Janus
use_default_menu: True

[printer Janus]
moonraker_host: 127.0.0.1
moonraker_port: 7125
moonraker_api_key: False
z_babystep_values: 0.01, 0.05
move_speed_xy: 500
move_speed_z: 300
power_devices: example1, example2，example3
titlebar_items: chamber, MCU, Pi
titlebar_name_type: None
calibrate_x_position: 100
calibrate_y_position: 100
screw_positions: "": ""

extrude_distances: 10, 25, 50, 100
extrude_speeds: 2, 5, 10, 15



### SENSORS
[menu __main sensors]
name: Sensors
icon: heat-up

[menu __main sensors chamber]
name: Chamber
icon: heat-up
method: printer.gcode.script
params: {"script":"_SHOW_SENSOR NAME='sht3x chamber_HUM'"}

[menu __main sensors ambient]
name: Ambient
icon: home
method: printer.gcode.script
params: {"script":"_SHOW_SENSOR NAME='sht3x ambient'"}


### LEDS
[menu __main leds]
name: LEDs
icon: light

[menu __main leds on]
name: Turn ON
icon: resume
method: printer.gcode.script
params: {"script":"SET_LED_EFFECT EFFECT=printing REPLACE=1"}

[menu __main leds off]
name: Turn OFF
icon: stop
method: printer.gcode.script
params: {"script":"STOP_LED_EFFECTS"}

[menu __main leds start]
name: Start
icon: heat-up
method: printer.gcode.script
params: {"script":"SET_LED_EFFECT EFFECT=print_start REPLACE=1"}

[menu __main leds cancel]
name: Cancel
icon: cancel
method: printer.gcode.script
params: {"script":"SET_LED_EFFECT EFFECT=cancel_print REPLACE=1"}

[menu __main leds done]
name: Done
icon: complete
method: printer.gcode.script
params: {"script":"SET_LED_EFFECT EFFECT=print_end REPLACE=1"}

[menu __main leds warm]
name: Warming
icon: heater
method: printer.gcode.script
params: {"script":"SET_LED_EFFECT EFFECT=warming_up REPLACE=1"}



### temperature

[menu __main temperature preheat_level]
name: Hotend 150C
icon: heat-up
method: printer.gcode.script
params: {"script":"SET_HEATER_TEMPERATURE HEATER=extruder TARGET=150"}


### motors
[menu __main tuning]
name: Motors tunning
icon: motor-off

# ---------------------------------------------------

[menu __main tuning sync_motors]
name: Sync Motors
icon: resume
method: printer.gcode.script
params: {"script":"SYNC_MOTORS"}

[menu __main tuning auto_speed]
name: Klipper Auto Speed
icon: hourglass
method: printer.gcode.script
params: {"script":"AUTO_SPEED"}

[menu __main tuning tmc_silent]
name: TMC AutoTune Silent
icon: speed-
method: printer.gcode.script
params: {"script":"AUTOTUNE_TMC_ALL_SILENT"}

[menu __main tuning tmc_auto]
name: TMC AutoTune Auto
icon: speed+
method: printer.gcode.script
params: {"script":"AUTOTUNE_TMC_ALL_AUTO"}

# ---------------------------------------------------



#~# --- Do not edit below this line. This section is auto generated --- #~#
#~#
#~# [main]
#~# print_sort_dir = date_desc
#~# 
#~# [displayed_macros Janus]
#~# data_sample = False
#~# draw_lines = False
#~# g32 = False
#~# print_end = False
#~# m106 = False
#~# print_start = False
#~# probecalibrate = False
#~# set_pause_at_layer = False
#~# set_pause_next_layer = False
#~# purge_done = False
#~# purge_more = False
#~# show_purge_menu = False
#~# 
#~# [graph Janus]
#~# temperature_sensor btt-mcu = False
#~# temperature_sensor ebb_ntc = False
#~# temperature_sensor chamber = False
#~# temperature_sensor soc = False
#~# heater_bed = False
#~#
